"""Podcasting 2.0 transcript parse (ported from Riff Mobile tests)."""

from riff.core.podcast_transcript import (
    active_cue_index,
    parse_transcript_document,
    pick_best_transcript,
    transcript_type_score,
)


def test_srt_coalesces_mid_sentence_cues():
    srt = """
1
00:00:00,000 --> 00:00:02,500
Welcome back to the show,

2
00:00:02,500 --> 00:00:04,000
today we talk transcripts.

3
00:00:06,000 --> 00:00:08,000
Second paragraph starts here.
"""
    cues = parse_transcript_document(srt, type_="application/srt")
    assert len(cues) == 2
    assert cues[0].start_sec == 0.0
    assert cues[0].text == (
        "Welcome back to the show, today we talk transcripts.")
    assert cues[1].start_sec == 6.0
    assert cues[1].end_sec == 8.0


def test_vtt_speakers_and_mmss():
    vtt = """WEBVTT

NOTE generated by test

00:01.000 --> 00:03.000
<v Alice>Hello there!

00:04.900 --> 00:07.000
<v Bob>Hi Alice.
"""
    cues = parse_transcript_document(vtt)
    assert len(cues) == 2
    assert cues[0].start_sec == 1.0
    assert cues[0].speaker == "Alice"
    assert cues[0].text == "Hello there!"
    assert cues[1].speaker == "Bob"


def test_json_segments():
    raw = """{"version":"1.0.0","segments":[
  {"speaker":"Host","startTime":0.5,"endTime":3.2,"body":"First line."},
  {"speaker":"Guest","startTime":4.0,"endTime":6.0,"body":"Second line."}
]}"""
    cues = parse_transcript_document(raw)
    assert len(cues) == 2
    assert cues[0].speaker == "Host"
    assert cues[0].start_sec == 0.5
    assert cues[1].text == "Second line."


def test_plain_and_html():
    cues = parse_transcript_document(
        "First paragraph of the episode.\n\nSecond paragraph.")
    assert len(cues) == 2
    assert cues[0].start_sec == -1
    assert cues[1].text == "Second paragraph."
    html = "<html><body><p>Para one.</p><p>Para <b>two</b>.</p></body></html>"
    html_cues = parse_transcript_document(html, type_="text/html")
    assert len(html_cues) == 2
    assert html_cues[0].text == "Para one."
    assert html_cues[1].text == "Para two."


def test_speaker_change_never_merged():
    srt = """
1
00:00:00,000 --> 00:00:01,000
A: I think

2
00:00:01,000 --> 00:00:02,000
B: no way
"""
    cues = parse_transcript_document(srt, type_="srt")
    assert len(cues) == 2
    assert cues[0].speaker == "A"
    assert cues[1].speaker == "B"


def test_pick_best_and_active_index():
    assert transcript_type_score("application/json", "x.json") > (
        transcript_type_score("text/vtt", "x.vtt"))
    url, type_ = pick_best_transcript([
        ("https://a.vtt", "text/vtt"),
        ("https://a.json", "application/json"),
        ("https://a.srt", "application/srt"),
    ])
    assert url.endswith(".json")
    cues = parse_transcript_document(
        '{"segments":[{"startTime":0,"body":"a"},{"startTime":5,"body":"b"}]}')
    assert active_cue_index(cues, 0.0) == 0
    assert active_cue_index(cues, 5.5) == 1
